SELECT BATCH_LIST.NAME AS NAME,
       BATCH_LIST.BEGIN_TIME AS BEGIN_TIME,
       BATCH_LIST.END_TIME AS END_TIME,
       BATCH_LIST.PROJECT_ID AS PROJECT_ID,
       BATCH_LIST.PARENT_ID AS PARENT_ID,
       BATCH_LIST.BATCH_STATUS AS BATCH_STATUS,
       BATCH_LIST.PROJECT_MEMBERSHIP_ID AS PROJECT_MEMBERSHIP_ID,
       BATCH_LIST.COMMENT AS COMMENT,
       BATCH_LIST.TIMELOG AS TIMELOG,
       BATCH_LIST.ISPICK AS ISPICK,
       BATCH_LIST.PARTNER_ID AS PARTNER_ID,
       BATCH_LIST.USERNAME AS USERNAME,
       CONTAINER.NAME AS CONTAINER_NAME,
       SOP.NAME AS SOP_NAME
FROM BIOBANK3.BATCH_LIST BATCH_LIST
LEFT JOIN BIOBANK3.CONTAINER CONTAINER ON CONTAINER.ID = BATCH_LIST.CONTAINER_ID
LEFT JOIN BIOBANK3.SOP SOP ON SOP.ID = BATCH_LIST.SOP_ID