SELECT BATCH_SAMPLE_LIST.BATCH_SAMPLE_STATUS AS BATCH_SAMPLE_STATUS,
       BATCH_SAMPLE_LIST.TIMELOG AS TIMELOG,
       BATCH_SAMPLE_LIST.USERNAME AS USERNAME,
       BATCH_SAMPLE_LIST.PROJECT_SAMPLEID AS PROJECT_SAMPLEID,
       BATCH_LIST.NAME AS BATCH_LIST_NAME,
       SAMPLE_10002.SAMPLEID AS SAMPLE_10002_SAMPLEID
FROM BIOBANK3.BATCH_SAMPLE_LIST BATCH_SAMPLE_LIST
INNER JOIN BIOBANK3.BATCH_LIST BATCH_LIST ON BATCH_LIST.ID = BATCH_SAMPLE_LIST.BATCH_ID
INNER JOIN BIOBANK3.SAMPLE_10002 SAMPLE_10002 ON SAMPLE_10002.ID = BATCH_SAMPLE_LIST.SAMPLE_ID