import:
  targetTable: "project.partner"
  operation: "UPSERT"
  batchSize: 100
  naturalKeys:
    - "name"
  columnMappings:
    - csv: "NAME"
      column: "name"
      type: "VARCHAR"
    - csv: "USERSTAMP"
      column: "userstamp"
      type: "VARCHAR"
    - csv: "CREATED"
      column: "created"
      type: "TIMESTAMP"
