import:
  targetTable: "sample.sample_property"
  operation: "UPSERT"
  batchSize: 100
  naturalKeys:
    - "sample_id"
    - "property_term"
  columnMappings:
    - csv: "SAMPLEID"
      column: "sample_id"
      type: "BIGINT"
      foreignKey:
        parentTable: "sample.sample"
        parentNaturalKey:
          - csv: "SAMPLEID"
            column: "sampleid"
    - csv: "PROPERTY_TERM"
      column: "property_term"
      type: "VARCHAR"
    - csv: "VALUE"
      column: "string_value"
      type: "VARCHAR"
      transformScript: "config/scripts/property_transform.js"
      transformFunction: "getStringValue"
    - csv: "VALUE"
      column: "integer_value"
      type: "INTEGER"
      transformScript: "config/scripts/property_transform.js"
      transformFunction: "getIntegerValue"
    - csv: "VALUE"
      column: "float_value"
      type: "REAL"
      transformScript: "config/scripts/property_transform.js"
      transformFunction: "getFloatValue"
    - csv: "VALUE"
      column: "choice_value"
      type: "VARCHAR"
      transformScript: "config/scripts/property_transform.js"
      transformFunction: "getChoiceValue"
