import:
  targetTable: "sample.sample"
  operation: "UPSERT"
  batchSize: 100
  naturalKeys:
    - "sampleid"
  columnMappings:
    - csv: "SAMPLEID"
      column: "sampleid"
      type: "VARCHAR"
    - csv: "SUBJECT"
      column: "subjectid"
      type: "VARCHAR"
    - csv: "SAMPLETYPE"
      column: "sample_type_id"
      type: "BIGINT"
      foreignKey:
        parentTable: "sample.sample_type"
        parentNaturalKey:
          - csv: "SAMPLETYPE"
            column: "name"
    - csv: "SAMPLE_STATUS"
      column: "sample_status"
      type: "VARCHAR"
      transformScript: "config/scripts/sample_transform.js"
      transformFunction: "transformStatus"
    - csv: "AMOUNT"
      column: "amount"
      type: "INTEGER"
    - csv: "CONCENTRATION"
      column: "concentration"
      type: "REAL"
    - csv: "REMARKS"
      column: "remarks"
      type: "VARCHAR"
    - csv: "CONTAINER_NAME"
      column: "container_id"
      type: "BIGINT"
      foreignKey:
        parentTable: "sample.container"
        parentNaturalKey:
          - csv: "CONTAINER_NAME"
            column: "name"
    - csv: "PLACECODE"
      column: "placecode"
      type: "VARCHAR"
    - csv: "PARENT_SAMPLEID"
      column: "parent_id"
      type: "BIGINT"
      foreignKey:
        parentTable: "sample.sample"
        parentNaturalKey:
          - csv: "PARENT_SAMPLEID"
            column: "sampleid"
    - csv: "USERNAME"
      column: "userstamp"
      type: "VARCHAR"
    - csv: "TIMELOG"
      column: "created"
      type: "TIMESTAMP"
