import:
  targetTable: "sample.task"
  operation: "UPSERT"
  batchSize: 100
  naturalKeys:
    - "name"
  columnMappings:
    - csv: "NAME"
      column: "name"
      type: "VARCHAR"
    - csv: "COMMENT"
      column: "description"
      type: "VARCHAR"
    - csv: "ISPICK"
      column: "task_type"
      type: "VARCHAR"
      transformScript: "config/scripts/task_transform.js"
      transformFunction: "transformTaskType"
    - csv: "BATCH_STATUS"
      column: "task_status"
      type: "VARCHAR"
      transformScript: "config/scripts/task_transform.js"
      transformFunction: "transformTaskStatus"
    - csv: "USERNAME"
      column: "assigned_to"
      type: "VARCHAR"
    - csv: "PROJECT_ABBREVIATION"
      column: "project_id"
      type: "BIGINT"
      foreignKey:
        parentTable: "project.project"
        parentNaturalKey:
          - csv: "PROJECT_ABBREVIATION"
            column: "name"
    - csv: "PARTNER_NAME"
      column: "partner_id"
      type: "BIGINT"
      transformScript: "config/scripts/work_list_transform.js"
      transformFunction: "transformPartnerName"
      foreignKey:
        parentTable: "project.partner"
        parentNaturalKey:
          - csv: "PARTNER_NAME"
            column: "name"
    - csv: "USERNAME"
      column: "userstamp"
      type: "VARCHAR"
    - csv: "BEGIN_TIME"
      column: "created"
      type: "TIMESTAMP"
      transformScript: "config/scripts/work_list_transform.js"
      transformFunction: "transformCreated"
